---
title: 
output:
  html_document:
    keep_md: true
---

# SkyWatchr

R wrapper for the [SkyWatch API] developed by [SkyWatch].

## Installation

If not installed yet, first install the `devtools` package:

```{r, eval = FALSE}
install.packages('devtools')
```

Then install the `SkyWatchr` package from this GitHub repository:

```{r, eval = FALSE}
devtools::install_github('amsantac/SkyWatchr')
```

## Usage

First load the SkyWatchr package:

```{r, eval = FALSE}
library(SkyWatchr)
```
Then store in an object your API key and try some queries with the `querySW` function:

```{r, eval = FALSE}
api_key <- "your_personal_alphanumeric_api_key"

# An oil refinery in Canada
querySW(api_key, level = 3, coordinates = "36.281389,-80.060278", times = 2015)

# One of the words largest landfills "Olusosun Dump" in Nigeria
querySW(api_key, coordinates = "6.566358,3.367358,6.586358,3.387358", times = "2015")

# The smoggiest city on Earth Ahvaz, Iran
querySW(api_key, level = 3, coordinates = "31.321119,48.676074", times = "2015-06")

# From SkyWatch GitHub repository examples
querySW(api_key, level = 2, coordinates = "-71.1043443253471,-42.3150676015829", times = "2009-12-25")
querySW(api_key, coordinates = "-71.1043443253471,-42.3150676015829", times = "2009-12-25")
```

[SkyWatch]: http://www.skywatch.co/
[SkyWatch API]: https://github.com/skywatchspaceapps/api/blob/master/README.md